### ISSUE TITLE
Cannot use import statement outside a module (NodeJS)

### ISSUE THREAD

**Issue by WathikAhmed** [FarmBot/farmbot-js#142]
Hi, I'm working with a group to make an open source project that makes a 3D render of the garden through photogrammetry. 

It is my understanding that I first have to:

1) Download the FarmbotJS file from github
2) Extract it
3) open visual studio code, start new terminal
4) execute this command `npm install farmbot`
5) then execute this command `npm run test`  (This command fails for me btw)
6) Then to run the first example code, i create a new file in the root of the farmbotJS directory that i recently downloaded and extracted, i called this file example.js and then I pasted these lines inside the file (I Changed the token to mine, as it works with the python API for farmbot) 
```
import { Farmbot } from "farmbot";

var SUPER_SECRET_TOKEN = "eyJ....7CiA";

let bot = new Farmbot({ token: SUPER_SECRET_TOKEN });

bot
  .connect()
  .then(function () {
    return bot.moveRelative({ x: 1, y: 2, z: 3, speed: 100 });
  });
```

7) Then in the visual studio code terminal, I ran example.js
8) Then I get the error 

```
PS C:\Users\Owner\Desktop\farmbot-js-main> node .\example.js
(node:14300) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
C:\Users\Owner\Desktop\farmbot-js-main\example.js:2
import { Farmbot } from "farmbot";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
PS C:\Users\Owner\Desktop\farmbot-js-main>
```
Heres a screenshot:
![error](https://user-images.githubusercontent.com/71957665/127261059-f877d207-362a-4caa-8035-8b9d33fee3a0.PNG)

Could you please help me with this? im looking to make a nice youtube tutorial for this once I get it working, so others can also follow the video steps to make it work, 

thanks in advance!

Regards,
Wathik

**Comment by RickCarlino** [comment]
@WathikAhmed The recommendation in the error message works on my machine, have you tried it?:

```
Warning: To load an ES module, set "type": "module" in the package.json
```

To add a `package.json` file, I create a package.json file via `npm init -y`, then I add the line `"type": "module"` to the package.json file. After that, it works.

Alternatively, if you don't like using ES modules, you could run:

```javascript
var Farmbot = require("farmbot").Farmbot;
```

The code example above requires no changes to `package.json`.


Please note that you can only choose one of these solutions. You cannot use `require` once `type` is set to `module`.
