### ISSUE TITLE
Turn on light

### ISSUE THREAD

**Issue by WathikAhmed** [FarmBot/farmbot-js#144]
Hi there, having difficulty turning on the farmbot lightstrip. its on pin number 7. 

currently im using the following but it dosent work

```
function toggleLight() {
  var farmbot123 = new fbjs.Farmbot({ token: TOKEN });

  farmbot123
  .connect()
  .then(function () {
    return farmbot123.togglePin({7});
  });
}
```

I can take photos and move the farmbot, so my connection and API are fine

**Comment by RickCarlino** [comment]
@WathikAhmed I would recomend changing from Javascript to Typescript, as the editor will give you many hints about the correct "shape" of data. It will also give nice error messages if you pass an incorrect parameter (FBJS is written in Typescript)

In the example above, you should change the code to look like this:

```javascript
return farmbot123.togglePin({ pin_number: 7 });
```

**Comment by WathikAhmed** [comment]
Thank you very much, it works now.

When you say change from Javascript to Typescript, what do I change exactly. Currently I run this from a simple html file. Thanks

**Comment by RickCarlino** [comment]
@WathikAhmed Typescript is a programming language that compiles to Javascript. It adds many helpful features such as error checking. Unfortunately, it is beyond the scope of this project for me to explain how to create a build system or structure a project. I recommend reading [the official tutorials](https://www.typescriptlang.org/docs/) and asking questions in Typescript-related communities if you have any questions.

Learning Typescript takes time, but you will find that it is well worth the effort and will make libraries like FarmBotJS easier to use in the long term. This is just a recommendation, though.
