### ISSUE TITLE
Execute a sequence by sending CeleryScript

### ISSUE THREAD

**Issue by WathikAhmed** [FarmBot/farmbot-js#148]
Hi, is it possible to execute a sequence by simply sending the CeleryScript?

Currently, the way I execute them is by:
1. Creating a script and sending it to store in the sequences folder. Which looks like this:

```
var celeryScript = { "kind": "wait", "args": { "milliseconds": 1000 } };
var sequenceName = "testName";
var settings = {
  "url": "https://my.farmbot.io/api/sequences",
  "method": "POST",
  "timeout": 0,
  "headers": {
    "Authorization": "Bearer " + TOKEN,
    "Access-Control-Allow-Origin": "*",
    "Content-Type": "application/json"
  },
  "data": JSON.stringify({
    "color": "red",
    "name": sequenceName,
    "pinned": false,
    "kind": "sequence",
    "body": [
      celeryScript
    ]
  }),
};

$.ajax(settings).done(function (response) {
  console.log(response);
});
```

2. Then I grab the response and retrieve the ID of the newly generated sequence.
3. Then I execute the sequence by its ID. This is how it looks:
```
var farmbot123 = new fbjs.Farmbot({ token: TOKEN });

	farmbot123
	.connect()
	.then(function () {
		return farmbot123.execSequence(NewSequenceID);
	}).then(function(farmbot123){
    console.log("Bot has stopped!");
  })
  .catch(function(error) {
    console.log("Something went wrong :(");
  });
```

So I was wondering if I could cut to the chase and simply send Celeryscript for it to execute? Thanks

**Comment by RickCarlino** [comment]
@WathikAhmed Yes, this is possible. This is how we send commands to the device from the FarmBot Web App. 

The only drawback is that you will need to write CeleryScript by hand. Writing CeleryScript by hand is best done with Typescript because the type checker can easily find your mistakes.

```typescript
import { uuid } from "farmbot";
import { your_farmbot } from "./some_other_file";

your_farmbot.send({
  kind: "rpc_request",
  args: {
    // Every `rpc_request` must have a long, unique `label`.
    // FBJS needs this proprty to know when a command finishes.
    label: uuid(),
    // This is a legacy field. Modern versions of FBOS do not
    // use it any more. You can set it to any number. It does
    // not matter.
    priority: 0
  },
  body: [
    {
      kind: "lua",
      args: {
        lua: "send_message('info', 'Hello, world!', 'toast')"
      }
    },
    {
      kind: "move_absolute",
      args: {
        speed: 100,
        location: {
          kind: "point",
          args: {
            pointer_id: 456,
            pointer_type: "Plant"
          }
        },
        offset: {
          kind: "coordinate",
          args: { x: 3, y: 3, z: 3 }
        },
      }
    }
  ]
}).then(() => { console.log("OK"); }, () => { console.log("ERROR"); });
```

**Comment by WathikAhmed** [comment]
Awesome thanks! It works.

Sample snippet from my code:
`// SEND AND Execute Sequence to Move x right and Take 1 image (SequenceName: moveAndShoot)
				function moveAndShoot() {
					var farmbot123 = new fbjs.Farmbot({ token: TOKEN });

					farmbot123
					.connect()
					.then(function () {
						return farmbot123.send({
							kind: "rpc_request",
							args: {
    // Every `rpc_request` must have a long, unique `label`.
    // FBJS needs this proprty to know when a command finishes.
								label: "moveAndShoot",
    // This is a legacy field. Modern versions of FBOS do not
    // use it any more. You can set it to any number. It does
    // not matter.
								priority: 0
							},
							body: [
							{
								"kind": "send_message",
								"args": {
									"message": "Chance App: Incrementing X and taking a photo (Please Do Not Touch)",
									"message_type": "success"
								}
							},
							{
								"kind": "wait",
								"args": {
									"milliseconds": 1000
								}
							},{
								"kind": "move",
								"args": {},
								"body": [
								{
									"kind": "axis_addition",
									"args": {
										"axis": "x",
										"axis_operand": {
											"kind": "numeric",
											"args": {
												"number": 50
											}
										}
									}
								},
								{
									"kind": "axis_addition",
									"args": {
										"axis": "y",
										"axis_operand": {
											"kind": "numeric",
											"args": {
												"number": 0
											}
										}
									}
								},
								{
									"kind": "axis_addition",
									"args": {
										"axis": "z",
										"axis_operand": {
											"kind": "numeric",
											"args": {
												"number": 0
											}
										}
									}
								}
								]
							},{
								"kind": "wait",
								"args": {
									"milliseconds": 500
								}
							},{
								"kind": "take_photo",
								"args": {}
							},{
								"kind": "wait",
								"args": {
									"milliseconds": 500
								}
							}
							]
						});
					}).then(function(farmbot123){
						console.log("Completed: moveAndShoot");
					})
						.catch(function(error) {
							console.log("Something went wrong :(");
						});
						}`
