### ISSUE TITLE
Disconnecting Farmbot mqtt connection

### ISSUE THREAD

**Issue by Ties17** [FarmBot/farmbot-js#154]
For a project I am automating the farmbot to execute tasks automatically via a cloud server solution. 
For this project I'd like to be able to stop the mqtt connection which is created with the farmbot.connect method. 
Is this possible and if so what is the best way to do so?

**Comment by RickCarlino** [comment]
Hi @Ties17 , thanks for reaching out it sounds like an interesting project.

If I am understanding you correctly, you want the ability to connect to MQTT, send a command and then disconnect. Am I understanding this correctly? You essentially are looking for a `farmbot.disconnect()` function, right?

I will need to do some research to see if it is possible in the current version of FBJS. If it is not possible, I am sure I can add it to a release for you. This is actually something I have never needed to do in my use of FarmBot.JS (and I think most customers leave the MQTT connection open).

One thing I would warn about, if this is what you are trying to do, is that FarmBot will get rate limited if you attempt to connect and disconnect from the MQTT server too often. This is a DDoS mitigation strategy.

**Comment by Ties17** [comment]
Hi @RickCarlino, Thanks for the fast reply.
Yes the `farmbot.disconnect()` function is essentially what I am looking for.
And yeah you understood me correctly, I want to connect to the mqtt server. Execute a sequence of events (to water or take photo's of the plants) and then disconnect. Mainly to make sure all connections that are created by my code are properly closed to not use any more computing resources then necessary.

So far we've used the connection like most people, and just kept it open. But we are now migrating it to a cloud service where the connection could prevent our container from being closed whilst being idle, which could lead to more costs for us.

Thanks for the warning. I'll keep it in mind to prevent the rate limiting from happening.

**Comment by RickCarlino** [comment]
@Ties17 You can disconnect from the server by using `bot.client.end();`. Alternatively, you could call `os.exit();` in the `.then(...)` section of the promise and let the OS handle closing the socket.

Please let me know if that works.

**Comment by Ties17** [comment]
@RickCarlino I tested the `bot.client.end()` method and that seems to work fine for my purposes. Thanks for your help :)
