### ISSUE TITLE
Node JS issue: ReferenceError: atob is not defined

### ISSUE THREAD

**Issue by RickCarlino** [FarmBot/farmbot-js#33]
# Problem:

 Running in a Node environment creates the following error:

```
ReferenceError: atob is not defined
    at Farmbot._decodeThatToken
```

# Fix

```
npm install atob --save
```
then before loading farmbot-js:

```
global.atob = require("atob");
```

**Comment by icerove** [comment]
not working

**Comment by RickCarlino** [comment]
@icerove Please provide more information.
 * What version of node are you running? (`node --version`)
 * What error message did you see (if any) when running `npm install atob --save`
 * What error do you see at runtime?
 * What does your code look like?

**Comment by WathikAhmed** [comment]
Where exactly do you put this line:

`global.atob = require("atob");`

**Comment by WathikAhmed** [comment]
Im looking to make a youtube video to make following the steps easier, could you help me with getting the farmbot js working, where can I contact you?
