### ISSUE TITLE
Packaging support for running this lib in the browser

### ISSUE THREAD

**Issue by kimptoc** [FarmBot/farmbot-js#49]
Hi,

Looking to do a simple FarmBot front end for "management" to use when showing our clients :)

Thinking it would be a single page app, with a login box and then some buttons to trigger a few sequences.

I could do it via direct calls using ajax myself, but since this lib is in place, it seems the way to go.

Don't care which package manager - don't do much front end generally.  Bower, browserify, yarn, jspm etc.

In fact, if packaging is not needed - please let me know :)

Thanks, Chris

**Comment by kimptoc** [comment]
Hmm - seems I misread the README- it should work in the browser, its just the node version that might need some work.

I am trying to use it via browserify, but getting this error in Chrome:

![image](https://user-images.githubusercontent.com/38746/27844788-6b870824-611e-11e7-9f84-54cd2618871c.png)

This comes from my basic page that allows you to login and get the token, but then gives the above error when trying to use it.

**Comment by kimptoc** [comment]
Got it working - I think - was passing wrong object from jQuery as the token :( .

**Comment by RickCarlino** [comment]
@kimptoc Sorry for the slow reply, it was a holiday here in the US. Did you get it working? FarmBot JS should work with Browserify, but we have only tested it with Webpack and Node.JS.

Make sure to pass the _encoded_ token into the `"Authorization"` header of the API request.

It will look something like this:

```
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ...(shortened for clarity)...x9rw
```

I have made an example node app that uses FarmBotJS to log onto an IRC chat room [here](https://github.com/FarmBot-Labs/FarmBot-Chat-Bot). 
Farmbot user @mdingena made one for telegram [here](https://github.com/mdingena/FarmGram).

I hope that helps! It's always fun to see the projects that people build with FarmBotJS. Please let me know if you require any other assistance.
