### ISSUE TITLE
Is there a way to access the photos that have been taken via this API?

### ISSUE THREAD

**Issue by kimptoc** [FarmBot/farmbot-js#70]
Or another API...

Many Thanks
Chris

**Comment by RickCarlino** [comment]
Hi @kimptoc -

This is possible.

1. [Create an API Token](https://github.com/FarmBot/Farmbot-Web-App#q-how-can-i-generate-an-api-token) and put it in the `Authorization:` header of all requests. Ex: `Authorization: Bearer <token>`
2. Perform a `GET` request to `/api/images`. If you have the image's ID already, you can `GET /api/images/123`, where `123` is the known image ID.

Notes:

 * This endpoint returns JSON, not binary images.
 * You can access the image via the `attachment_url` property of image resources.

Does that help?

**Comment by kimptoc** [comment]
Yes - that sounds great.  Will have a play :)

**Comment by WathikAhmed** [comment]
@kimptoc Did you figure it out? Could I get the code for this please? Thanks

**Comment by RickCarlino** [comment]
@WathikAhmed I don't have an example snippet on hand, but this is done easily via any HTTP client you prefer. I recommend Axios.

 * A list of HTTP endpoints can be found [here](https://gist.github.com/RickCarlino/10db2df375d717e9efdd3c2d9d8932af).
 * Once you install an HTTP client, you need to add an `Authorization` header that contains your auth token. Example: `Authorization: bearer XYZ` where XYZ is your API token.
 * An example that uses CURL to download images can be found [here](https://forum.farmbot.org/t/how-to-download-multiple-images-from-the-camera-at-once/7239/9?u=rickcarlino).
