### ISSUE TITLE
Does this library work with the current OS/cloud platform?

### ISSUE THREAD

**Issue by kimptoc** [FarmBot/farmbot-js#72]
Hi,

When I try to connect today, I get a timeout:
```
(node:47641) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to connect to MQTT after 30000 ms.
```

Get something similar via a browserified old version:

```
WebSocket connection to 'wss://brisk-bear.rmq.cloudamqp.com/' failed: Error during WebSocket handshake: Unexpected response code: 200
WebSocketStream @ farmbot-browserified.js:13511
buildBuilderBrowser @ farmbot-browserified.js:12753
wrapper @ farmbot-browserified.js:12592
MqttClient._setupStream @ farmbot-browserified.js:11766
MqttClient._reconnect @ farmbot-browserified.js:12094
(anonymous) @ farmbot-browserified.js:12109
```

I appreciate that the move to RabbitMQ has begun and so this probably just needs to catch up...  but thought I'd check :)

Thanks.

**Comment by RickCarlino** [comment]
@kimptoc Thanks for bringing this to our attention. There have definitely been some adjustments needed after the switch- this might be one of them. Although we do support Node.JS, we don't actively test against Node setups on a day-to-day basis. My suspicion is that FarmBot JS is erroneously setting the connection protocol to `wss://` when it should actually be `mqtt://`. I will investigate the issue further and let you know what I find. Thanks again for letting us know about this.

**Comment by RickCarlino** [comment]
@kimptoc A few things:

**Comment by RickCarlino** [comment]
@kimptoc I have just published the fix to NPM as version `5.0.2-rc4`. Please update your dependencies to this version. I tested locally on Node after the fix and was able to connect.

The `connect()` method was erroneously trying to connect via Websockets rather than traditional MQTT.

I look forward to seeing what you build with FarmBot.JS. :smile:

**Comment by kimptoc** [comment]
Awesome @RickCarlino - that works much better, in node - trying to do a test [Alexa voice skill](https://bitbucket.org/kimptoc/serverless-farmbot-alexa/overview) to control our Farmbot...  :)

I also have an [alternate webui](https://github.com/kimptoc/farmbot-simple-client) (simplified)  , using this lib via browserify.  Its not just working - looks like the old one 'require' 'd itself at the end but the new one doesn't - does that make sense?

Thanks.

**Comment by kimptoc** [comment]
Ignore my comment about about the webui - I was browserifying it wrongly :(

**Comment by RickCarlino** [comment]
@kimptoc I'm glad it's working. The Web UI looks great! I'm sure users on the main forum would love to see the Alexa skill when you get it running. Good luck! Let us know if you have any other questions.
