### ISSUE TITLE
Trouble compiling or running in browser

### ISSUE THREAD

**Issue by muenchris** [FarmBot/farmbot-js#93]
First of all: I love the Farmbot!

My company is in the IoT business and I would like to connect the Farmbot to our IoT Solution.
Also I am super happy to see that you embrace TypeScript - which we also use for our JS engine.

but...

I cannot get the JavaScript libraries to work correctly in a (chrome) browser.
According to your readme - only a browser with WebSockets, JSON and native Promise is required - all three is available in Chrome.

Still it fails to run. Can you list the other requirements needed?
For example: 
MQTT is required
ATOB is required
what else is missing?

It loads and works fine in NodeJS but I don't want to carry around this huge amount of NodeJS...schtuff:)

could you create a sample project that runs (with as little code/libraries as possible)?
Eventually I will run this in C# but before I convert the project, I like to see it run in a browser first.

Thanks,
Chris
C-Labs

**Comment by RickCarlino** [comment]
@muenchris What sort of errors do you see in the JS console? How are you building the project?

**Comment by muenchris** [comment]
Hi Rick,

I am working with Visual Studio 2017- not using any console just the TS Compiler.
In order to compile the TS, I need the type definition of the MQTT library - do you have a reference to this? 
I was able to work around it (not sure if it works) by changing this in your farmbot.ts:

```
//import { connect, Client as MqttClient, IClientOptions } from "mqtt";
declare var MqttClient
```
It at least compiles then

Also, you use "array.includes" and "new Promise", which does not compile correctly in the latest TypeScript 2.8.1 even with ES6 on. Still try to figure out how to convince VS2017 to just accept this.

The way our plugins work is that they have a back-end part (in C#) and a front end part in TypeScript/JS (if the plugin requires it). The TS part is compiled to JS and stored as embedded resources of the backend DLL. 
Once a user logs into our browser runtime, the runtime requests the compiled JS files from the plugin and instantiates the classes. (our system is mesh based - so the plugin might not be on the server that serves the browser but somewhere on the mesh)

That means I need to be able to compile the TS to JS, then call your classes from my js file:

Our Main Plugin TS class looks like this. All I need to do is to get somehow the "DoConnect()" to work:

```
///<reference path='cdeCore-4.0.0.d.ts'/>
///<reference path='cdeNMIBaseControls-4.0.0.d.ts'/>

//////// The next lines are the complicated onces - none of them work correctly
///<reference path='ts\farmbot.d.ts'/>
//import { Farmbot } from "./farmbot";
declare var Farmbot: any;

module CDMySensors {    // Corresponds to the C# backend namespace
    export var eTheSensors: string = "CDMySensors.TheSensors";

    export class TheSensors {   //corrensponds to the C# class that "owns" this code
        MyBaseEngine: cde.TheBaseEngine = null;
        public static MyEngine: TheSensors;
        public static IsReady: boolean = false;

        public static StartEngine() {   //Will be called by our runtime when a user has successfully logged in
            TheSensors.MyEngine = new TheSensors();
            debugger;
            cdeNMI.TheNMIService.cdeGetScript("/P196/JS/mqtt.min.js", () => {   //Our way to request a script file from the plugin somewhere in the mesh and than instantiate it in the browser (basically an async way to load scripts on demand and add them to the header of the current doc in the browser)
                debugger;
                cdeNMI.TheNMIService.cdeGetScript("/P196/JS/browser-atob.js", () => {
                    debugger;
                    cdeNMI.TheNMIService.cdeGetScript("farmbot.js", () => { // Eventually I want to combine all JS files into one file that I don't have to daisy-chain the async loading
                        debugger;
                        TheSensors.IsReady = true;
                        cde.MyBaseAssets.MyEngines[eTheSensors].FireEngineIsReady();
                        cdeNMI.FireEvent(false, "EngineReady", eTheSensors);
                    });
                });
            });
        }


        public static DoConnect() { //This will be called from the C# backend class - well there is a lot of plumbing going on but in the end this call is just executed
            if (!TheSensors.IsReady)
                return;
            cdeNMI.ShowToastMessage("Connecting to Farmbot...");

            var f = new Farmbot({
                secure: true,
                token: "MyFarmbitToken"
            });

            f.connect().then(() => console.log("OK"), (e) => (console.dir(e)));

            f.on("*", (x) => {
                console.log(x);
            });

            f.on("online", () => {
                console.log("ONLINE");
            });
            f.on("offline", () => {
                console.log("offline");
            });
            f.on("status", () => {
                console.log("status");
            });
        }

        constructor() {
            this.MyBaseEngine = cdeCommCore.StartNewEngine(CDMySensors.eTheSensors);
            this.MyBaseEngine.RegisterIncomingMessage((pProcessMessage: cde.TheProcessMessage) => { this.HandleMessage(pProcessMessage); });
        }

        HandleMessage(pProcessMessage: cde.TheProcessMessage) {   //Message Handler for C-DEngine Messages
            var pMSG: cde.TSM = pProcessMessage.Message;
            if (!pMSG) return;

            var tCmd: string[] = pMSG.TXT.split(':');
            switch (tCmd[0]) {
                default:
                    break;
            }
        }
    }
}

```

Two things might help us:

1) Wrapping the Farmbot classes in a "module"
2) creating a single TS file with all TS parts - just for integration with other systems (otherwise I have to do this:))

Most likely #1 is already all I need in order for this to work correctly

I will continue to experiment....

Cheers,
Chris

**Comment by RickCarlino** [comment]
@muenchris 

 >  I need the type definition of the MQTT library - do you have a reference to this?

The authors of MQTT.js do support TS typings. You can find them [here](https://github.com/mqttjs/MQTT.js/blob/master/types/index.d.ts). As you can see from the [number of files](https://github.com/mqttjs/MQTT.js/tree/master/types/lib), keeping a local copy of these dependecies might be difficult. Most modern bundlers (webpack, browserify, parcel) will handle this for you transparently and deal with the recursive nature of subdependencies.

 > you use "array.includes" and "new Promise", which does not compile correctly in the latest TypeScript 2.8.1 even with ES6 on

We also use `2.8.1`. You will need to update your `tsconfig` to support `es2017`:

```
    "lib": [
      "es2017",
      "dom"
    ]
```

 > The way our plugins work is that they have a back-end part (in C#) and a front end part in TypeScript/JS (if the plugin requires it). The TS part is compiled to JS and stored as embedded resources of the backend DLL.

Would exporting the `Farmbot` class as a global help? You could likely write a local type definition to accomodate your build system, although you would need to update your FBJS versions manually every time.

What other libraries does your project currently use and how are you supporting Typescript in those cases? I would be willing to look into the matter further.

 > I need to be able to compile the TS to JS, then call your classes from my js file

You could clone the repository locally and compile based off of the `tsconfig` in our project, but you will still require ES6 module support.

Our current build system supports Typescript projects out of the box as long as there is a module bundler present.

I would be willing to add a global export if it helps- I have actually meant to support it for some time now, but it complicates the build and no on has requested it (the majority of FBJS users use Browserify or Webpack).

 > creating a single TS file with all TS parts

Are you aware of any automated ways to do this via `tsc`? I know `--outFile` allows compilation into a single `.js` file, but that might not work for what you are asking.

Please let me know and I can investigate the matter further.

**Comment by muenchris** [comment]
yes a global export would help. Thank you

yes I played with --outfile. I found it harder to debug in the browser later but before we ship we might do this

Cheers
Chris

**Comment by muenchris** [comment]
Thanks..but the single file is now highly optimized...how do I use that within a JavaScript File or my TypeScript project? (sorry I guess I am missing something somewher:))

Thanks
Chris

**Comment by RickCarlino** [comment]
@muenchris Within a javascript file you would just call `new fbjs.Farmbot({...})`. On the Typescript side you will probably need to:

 * Use the `any` keyword a lot -OR-
 * Write a custom  typing to `declare namespace fbjs {}`.

It will probably look something like this:

```typescript
// file: MY_CUSTOM_FARMBOT_TYPING.d.ts
declare class Farmbot {
  /** You will need to tweak the declaration in `farmbot.d.ts` since
   * you're using "internal" (non-ES6) modules.
   *
   * dist/farmbot.d.ts offers a good starting point. You may need to use the
   * `any` keyword for some types.
   */
}

declare namespace fbjs {
  export class Farmbot
  // Add any other types you need here, although `Farmbot` may be all you need for your project.
}
```
It's not a perfect solution, but it will give you some level of predictability in your builds. Non-ES6 Typescript environments are becoming increasingly uncommon (for example, `TSC` gave me a deprecation warning when I tried to declare the example above as an internal module). I can't guarantee too much support beyond this, but please let me know if you have any other questions and I can try my best to get you up and running.

**Comment by muenchris** [comment]
thanks for your help...lets see how far I get
