### ISSUE TITLE
js api executeSequence requires ID..but where to get?

### ISSUE THREAD

**Issue by muenchris** [FarmBot/farmbot-js#95]
I have my nodeJS client working now and I can do almost all I want to do...except starting sequences.

The "executeSequence" requires an ID according to the farmbot.d.ts
    /** Execute a sequence by its ID on the API. */
    execSequence(sequence_id: number): Promise<{}>;

But how I can find the ID of a sequence? The sequences are not listed in the "getState" or in the getStatus.

The WebUI also does not show the sequence ID.

Is this missing in the API or am I overlooking something?

Thanks
Chris

**Comment by RickCarlino** [comment]
@muenchris Great question. It's important to remember that _commands_ are controlled by Farmbot.JS (MQTT) and _information_ is managed by the API (REST/HTTP). So in your case, you will need to download the sequence ID (information) via REST, and then feed that information into `execSequence` (a command). 

 > how I can find the ID of a sequence?

You can view a list of all sequences (in JSON format) by:

1. [Creating an API token](https://github.com/RickCarlino/farmbot-web-app#q-how-can-i-generate-an-api-token)
2. Performing a GET request to `/api/sequences` (Make sure to [set the correct `Content-Type` and `Authorization` header](https://github.com/RickCarlino/farmbot-web-app#via-jquery).

**Comment by RickCarlino** [comment]
As a side note, future versions of FarmBot.JS may eliminate this two step process (it's been requested by a few developers).

There is no timeline on a release yet. If you have any issues downloading the data from the API, please [open an issue on the Web-App repo](https://github.com/FarmBot/Farmbot-Web-App/issues/new?title=Cant%20download%20sequences%20via%20the%20API))

**Comment by muenchris** [comment]
I got the token - otherwise all the NodeJS calls would not work right:)

The link you posted to "set the correct content type and Authorization header" does not go to the correct page. At least it does not tell what content-type and AuthHeader you expect.

Thanks
Chris

**Comment by muenchris** [comment]
My bad...found it :)
